version: '3'

networks:
  nginx-php-mysql8-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - php-service
    networks:
      - nginx-php-mysql8-node

  # php
  php-service:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/project
    depends_on:
      - mysql8-service
    networks:
      - nginx-php-mysql8-node

  # mysql
  mysql8-service:
    image: mysql:8
    container_name: mysql8-container
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - nginx-php-mysql8-node

  # node
  node-service:
    container_name: node-container
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:4200"
    volumes:
      - ./frontend:/app
    networks:
      - nginx-php-mysql8-node